export interface Contact {
  id: string;
  name: string;
  email: string;
  status: 'lead' | 'client' | 'other';
}

export const contacts: Contact[] = [
  {
    id: '1',
    name: 'Sarah Chen',
    email: 's.chen@techcorp.com',
    status: 'other',
  },
  {
    id: '2',
    name: 'Marcus Rodriguez',
    email: 'marcus.r@innovate.io',
    status: 'lead',
  },
  {
    id: '3',
    name: 'Emily Thompson',
    email: 'emily.thompson@design.co',
    status: 'client',
  },
  { id: '4', name: 'David Kim', email: 'd.kim@startup.dev', status: 'other' },
  {
    id: '5',
    name: 'Alexandra Williams',
    email: 'alex.williams@global.net',
    status: 'lead',
  },
  {
    id: '6',
    name: "Michael O'Connor",
    email: 'm.oconnor@solutions.biz',
    status: 'client',
  },
  {
    id: '7',
    name: 'Priya Patel',
    email: 'priya.patel@enterprisetech.com',
    status: 'other',
  },
  {
    id: '8',
    name: 'Liam Nguyen',
    email: 'liam.nguyen@creativelabs.org',
    status: 'lead',
  },
  {
    id: '9',
    name: 'Olivia Garcia',
    email: 'olivia.garcia@medicorps.com',
    status: 'client',
  },
  {
    id: '10',
    name: 'Noah Smith',
    email: 'noah.smith@fintechhub.io',
    status: 'other',
  },
  {
    id: '11',
    name: 'Isabella Rossi',
    email: 'isabella.rossi@eurodesign.eu',
    status: 'lead',
  },
  {
    id: '12',
    name: 'Ethan Lee',
    email: 'ethan.lee@edusolutions.edu',
    status: 'client',
  },
  {
    id: '13',
    name: 'Mia Johnson',
    email: 'mia.johnson@retailers.com',
    status: 'other',
  },
  {
    id: '14',
    name: 'Lucas Brown',
    email: 'lucas.brown@logistics.net',
    status: 'lead',
  },
  {
    id: '15',
    name: 'Sofia Martinez',
    email: 'sofia.martinez@travelco.com',
    status: 'client',
  },
  {
    id: '16',
    name: 'Benjamin Clark',
    email: 'ben.clark@consultingpro.biz',
    status: 'other',
  },
  {
    id: '17',
    name: 'Ava Wilson',
    email: 'ava.wilson@greenenergy.org',
    status: 'lead',
  },
  {
    id: '18',
    name: 'William Evans',
    email: 'will.evans@buildersinc.com',
    status: 'client',
  },
  {
    id: '19',
    name: 'Charlotte King',
    email: 'charlotte.king@publishinghouse.com',
    status: 'other',
  },
  {
    id: '20',
    name: 'James Scott',
    email: 'james.scott@cyberdefense.io',
    status: 'lead',
  },
  {
    id: '21',
    name: 'Harper Davis',
    email: 'harper.davis@cloudtech.com',
    status: 'client',
  },
  {
    id: '22',
    name: 'Mason Taylor',
    email: 'mason.taylor@dataanalytics.org',
    status: 'other',
  },
  {
    id: '23',
    name: 'Evelyn Anderson',
    email: 'evelyn.anderson@mobilesolutions.net',
    status: 'lead',
  },
  {
    id: '24',
    name: 'Logan Thomas',
    email: 'logan.thomas@airesearch.edu',
    status: 'client',
  },
  {
    id: '25',
    name: 'Abigail Jackson',
    email: 'abigail.jackson@healthtech.io',
    status: 'other',
  },
  {
    id: '26',
    name: 'Jacob White',
    email: 'jacob.white@securityfirm.biz',
    status: 'lead',
  },
  {
    id: '27',
    name: 'Emma Harris',
    email: 'emma.harris@fashionbrand.com',
    status: 'client',
  },
  {
    id: '28',
    name: 'Alexander Martin',
    email: 'alex.martin@robotics.tech',
    status: 'other',
  },
  {
    id: '29',
    name: 'Madison Thompson',
    email: 'madison.thompson@socialmedia.co',
    status: 'lead',
  },
  {
    id: '30',
    name: 'Elijah Garcia',
    email: 'elijah.garcia@gamedev.studio',
    status: 'client',
  },
  {
    id: '31',
    name: 'Scarlett Martinez',
    email: 'scarlett.martinez@biotech.org',
    status: 'other',
  },
  {
    id: '32',
    name: 'Daniel Robinson',
    email: 'daniel.robinson@aerospace.gov',
    status: 'lead',
  },
  {
    id: '33',
    name: 'Grace Clark',
    email: 'grace.clark@renewableenergy.net',
    status: 'client',
  },
  {
    id: '34',
    name: 'Henry Rodriguez',
    email: 'henry.rodriguez@foodtech.com',
    status: 'other',
  },
  {
    id: '35',
    name: 'Chloe Lewis',
    email: 'chloe.lewis@virtualreality.io',
    status: 'lead',
  },
  {
    id: '36',
    name: 'Sebastian Lee',
    email: 'sebastian.lee@blockchain.dev',
    status: 'client',
  },
  {
    id: '37',
    name: 'Victoria Walker',
    email: 'victoria.walker@smartcity.gov',
    status: 'other',
  },
  {
    id: '38',
    name: 'Owen Hall',
    email: 'owen.hall@quantumcomputing.edu',
    status: 'lead',
  },
  {
    id: '39',
    name: 'Zoey Allen',
    email: 'zoey.allen@ecommerce.shop',
    status: 'client',
  },
  {
    id: '40',
    name: 'Carter Young',
    email: 'carter.young@spacetech.org',
    status: 'other',
  },
  {
    id: '41',
    name: 'Lily Hernandez',
    email: 'lily.hernandez@cleantech.com',
    status: 'lead',
  },
  {
    id: '42',
    name: 'Grayson King',
    email: 'grayson.king@nanotech.lab',
    status: 'client',
  },
  {
    id: '43',
    name: 'Layla Wright',
    email: 'layla.wright@digitalmarketing.agency',
    status: 'other',
  },
  {
    id: '44',
    name: 'Wyatt Lopez',
    email: 'wyatt.lopez@autonomous.vehicles',
    status: 'lead',
  },
  {
    id: '45',
    name: 'Aria Hill',
    email: 'aria.hill@machinelearning.ai',
    status: 'client',
  },
  {
    id: '46',
    name: 'Luke Scott',
    email: 'luke.scott@cybersecurity.pro',
    status: 'other',
  },
  {
    id: '47',
    name: 'Nora Green',
    email: 'nora.green@sustainabletech.org',
    status: 'lead',
  },
  {
    id: '48',
    name: 'Julian Adams',
    email: 'julian.adams@internetofthings.net',
    status: 'client',
  },
  {
    id: '49',
    name: 'Stella Baker',
    email: 'stella.baker@augmentedreality.co',
    status: 'other',
  },
  {
    id: '50',
    name: 'Maverick Gonzalez',
    email: 'maverick.gonzalez@3dprinting.tech',
    status: 'lead',
  },
  {
    id: '51',
    name: 'Hazel Nelson',
    email: 'hazel.nelson@smartgrid.energy',
    status: 'client',
  },
  {
    id: '52',
    name: 'Easton Carter',
    email: 'easton.carter@geneticengineering.bio',
    status: 'other',
  },
  {
    id: '53',
    name: 'Violet Mitchell',
    email: 'violet.mitchell@neuralnetworks.ai',
    status: 'lead',
  },
  {
    id: '54',
    name: 'Colton Perez',
    email: 'colton.perez@drone.technology',
    status: 'client',
  },
  {
    id: '55',
    name: 'Aurora Roberts',
    email: 'aurora.roberts@quantumsensors.lab',
    status: 'other',
  },
  { id: 'hc1',  name: 'Margaret Holloway', email: 'margaret.holloway@email.com',  status: 'client' },
  { id: 'hc2',  name: 'Derek Okafor',      email: 'derek.okafor@email.com',       status: 'client' },
  { id: 'hc3',  name: 'Sofia Reyes',       email: 'sofia.reyes@email.com',        status: 'client' },
  { id: 'hc4',  name: 'Tyler Nguyen',      email: 'tyler.nguyen@email.com',       status: 'client' },
  { id: 'hc5',  name: 'Priya Chandran',    email: 'priya.chandran@email.com',     status: 'client' },
  { id: 'hc6',  name: 'James Whitfield',   email: 'james.whitfield@email.com',    status: 'lead'   },
  { id: 'hc7',  name: 'Linda Castillo',    email: 'linda.castillo@email.com',     status: 'client' },
  { id: 'hc8',  name: 'Raymond Foster',    email: 'raymond.foster@email.com',     status: 'client' },
  { id: 'hc9',  name: 'Aisha Obi',         email: 'aisha.obi@email.com',          status: 'other'  },
  { id: 'hc10', name: 'Harold Simmons',    email: 'harold.simmons@email.com',     status: 'client' },
  { id: 'hc11', name: 'Carol Jennings',    email: 'carol.jennings@email.com',     status: 'client' },
  { id: 'hc12', name: 'Ben Kowalski',      email: 'ben.kowalski@email.com',       status: 'client' },
  { id: 'hc13', name: 'Megan Torres',      email: 'megan.torres@email.com',       status: 'client' },
  { id: 'hc14', name: 'Oliver Grant',      email: 'oliver.grant@email.com',       status: 'lead'   },
  { id: 'hc15', name: 'Dana Schwartz',     email: 'dana.schwartz@email.com',      status: 'client' },
];
